CREATE TABLE IF NOT EXISTS table_games (
id INT NOT NULL ,
`date` VARCHAR(255) ,
home_team_score INT ,
period INT ,
postseason VARCHAR(255) ,
season INT ,
status VARCHAR(255) ,
time VARCHAR(255) ,
visitor_team_score INT ,
`home_team.id` INT ,
`home_team.abbreviation` VARCHAR(255) ,
`home_team.city` VARCHAR(255) ,
`home_team.conference` VARCHAR(255) ,
`home_team.division` VARCHAR(255) ,
`home_team.full_name` VARCHAR(255) ,
`home_team.name` VARCHAR(255) ,
`visitor_team.id` INT ,
`visitor_team.abbreviation` VARCHAR(255) ,
`visitor_team.city` VARCHAR(255) ,
`visitor_team.conference` VARCHAR(255) ,
`visitor_team.division` VARCHAR(255) ,
`visitor_team.full_name` VARCHAR(255) ,
`visitor_team.name` VARCHAR(255) ,
PRIMARY KEY (id));